// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type NewTodo struct {
	Class       string    `json:"class"`
	Kind        string    `json:"kind"`
	Deadline    time.Time `json:"deadline"`
	Name        *string   `json:"name"`
	Description *string   `json:"description"`
}

type Todo struct {
	Class       string    `json:"class"`
	Kind        string    `json:"kind"`
	Deadline    time.Time `json:"deadline"`
	IsDone      bool      `json:"isDone"`
	Name        *string   `json:"name"`
	Description *string   `json:"description"`
}

type User struct {
	Name   *string `json:"name"`
	School string  `json:"school"`
}
